insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (1, 'Triamterene and Hydrochlorothiazide', 'rutrum nulla nunc purus phasellus in felis donec', 122, 3, 46);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (2, 'Neutrogena Rapid Clear 2 in 1 Fight and Fade Toner', 'dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum', 195, 3, 22);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (3, 'NUCYNTA', 'volutpat dui maecenas tristique est et tempus semper est', 110, 3, 98);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (4, 'Didanosine', 'ligula nec sem duis aliquam convallis nunc proin at turpis', 58, 10, 81);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (5, 'Equaline Antacid', 'suscipit ligula in lacus curabitur at ipsum', 162, 5, 71);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (6, 'Methylphenidate Hydrochloride', 'enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin', 194, 7, 3);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (7, 'Hydromorphone Hydrochloride', 'nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim', 174, 4, 6);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (8, 'Ammens Medicated Powder Original', 'phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie', 143, 5, 46);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (9, 'Nu Skin Nu Colour', 'venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat', 155, 8, 62);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (10, 'Furosemide', 'pellentesque ultrices mattis odio donec vitae nisi', 192, 10, 12);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (11, 'GUNA-IL 7', 'vel lectus in quam fringilla rhoncus mauris', 93, 2, 87);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (12, 'Acid Reducer', 'faucibus accumsan odio curabitur convallis duis consequat dui nec nisi', 156, 8, 37);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (13, 'Vanos', 'etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem', 125, 0, 27);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (14, 'Doxycycline Hyclate', 'dapibus nulla suscipit ligula in lacus curabitur at ipsum', 179, 6, 42);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (15, 'Neutrogena Naturals Acne Foaming Scrub', 'cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque', 130, 10, 94);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (16, 'SoftCIDE-ES', 'in congue etiam justo etiam pretium iaculis justo in hac habitasse', 170, 0, 81);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (17, 'Lorazepam', 'sit amet cursus id turpis integer aliquet', 160, 5, 27);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (18, 'Pure and Clear Exfoliating Wash', 'rutrum rutrum neque aenean auctor gravida sem praesent id massa', 158, 3, 40);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (19, 'Pantoprazole Sodium', 'ultrices phasellus id sapien in sapien iaculis congue vivamus', 55, 4, 69);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (20, 'Fluoxetine', 'nisi venenatis tristique fusce congue diam id', 112, 7, 96);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (21, 'Metronidazole', 'sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus', 97, 9, 6);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (22, 'Divalproex Sodium', 'id consequat in consequat ut nulla sed accumsan felis ut at', 168, 4, 99);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (23, 'Clear Eyes Complete 7 Symptom Relief', 'faucibus orci luctus et ultrices posuere cubilia curae duis', 123, 3, 64);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (24, 'Tussin CF', 'diam erat fermentum justo nec condimentum', 131, 6, 13);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (25, 'Fluconazole', 'neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis', 134, 2, 43);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (26, 'medroxyprogesterone acetate', 'neque duis bibendum morbi non quam', 68, 9, 11);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (27, 'Quetiapine fumarate', 'eu felis fusce posuere felis sed lacus morbi sem', 160, 9, 15);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (28, 'adult tussin', 'sapien urna pretium nisl ut volutpat', 144, 3, 34);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (29, 'Nail Fungus Control', 'tincidunt eget tempus vel pede morbi porttitor lorem id', 123, 7, 16);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (30, 'bareMinerals Prime Time BB Primer', 'sit amet consectetuer adipiscing elit proin interdum mauris non', 61, 8, 1);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (31, 'DawnMist Deodorant Bar No. 5', 'ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non', 159, 8, 65);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (32, 'Pediacare Childrens Allergy', 'tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum', 103, 1, 100);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (33, 'White Alder', 'lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non', 112, 1, 86);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (34, 'Actos', 'consequat morbi a ipsum integer a nibh in quis justo', 71, 6, 25);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (35, 'E-Z-Cat Dry', 'ut dolor morbi vel lectus', 111, 0, 95);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (36, 'Carbon Dioxide-Oxygen Mixture', 'fringilla rhoncus mauris enim leo rhoncus sed', 174, 7, 96);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (37, 'Naratriptan', 'justo etiam pretium iaculis justo in hac habitasse', 84, 9, 71);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (38, 'SEROQUEL', 'in lectus pellentesque at nulla suspendisse potenti cras in purus', 143, 2, 9);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (39, 'Betamethasone Valerate', 'felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu', 125, 4, 89);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (40, 'Tolterodine Tartrate', 'a ipsum integer a nibh', 153, 8, 44);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (41, 'Fentanyl', 'semper porta volutpat quam pede lobortis ligula sit amet eleifend pede', 143, 5, 59);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (42, 'Solmeet denti doctor', 'justo sollicitudin ut suscipit a feugiat et eros vestibulum', 135, 1, 51);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (43, 'Ibuprofen', 'nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh', 83, 1, 89);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (44, 'SkinMedica Purifying Toner', 'commodo placerat praesent blandit nam nulla integer pede justo lacinia', 58, 9, 91);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (45, 'Helium Oxygen Mix', 'sit amet eleifend pede libero quis orci nullam molestie', 78, 4, 34);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (46, 'DILTZAC', 'fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat', 51, 5, 10);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (47, 'Day Time Cold and Flu Relief', 'mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus', 85, 3, 35);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (48, 'Hair Regrowth Treatment for Men', 'dui vel sem sed sagittis nam congue risus semper porta volutpat', 117, 9, 1);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (49, 'TC EnrichedFoam', 'neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet', 146, 1, 30);
insert into t_arme (arme_id, nom, description, prix, `force`, coups_max) values (50, 'Avapro', 'sed ante vivamus tortor duis mattis egestas metus aenean fermentum', 146, 3, 97);
